### ISSUE TITLE
Running without PHPUnit causes an error

### ISSUE THREAD

**Issue by catharsisjelly** [silverstripe/gha-ci#71]
Trying to run this CI without running PHPUnit as there are no tests for the module and it's generating this error

```
CI: .github#L1
Error when evaluating 'strategy' for job 'tests'. silverstripe/gha-ci/.github/workflows/ci.yml@1.3.7 (Line: 113, Col: 15): Matrix must define at least one vector
```

Here is a [direct link](https://github.com/catharsisjelly/silvercommerce-settings/actions/runs/5365078936) to the action but if that does not work then my `yml` is included below

```yml
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      phpunit: false
```
